# From dockerhub we select the image that we need to use
FROM node

# As the second instruction, we tell to docker wich files must live in the image
# With this command we clone all files to the docker image
COPY . .